version: '3'
services:
  mongo:
    image: mongo
    container_name: 'mongodb'
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass  
  app:
    build: .
    container_name: my-app
    ports:
      - "5000:5000"   

